### PR TITLE
RDK Workshop local build

### PR DESCRIPTION
**Pull request by mazaruz**
*Description of changes:*

Based on the request for the RDK workshop, I've modified the template so that everyone can rebuild the RDK lab at home.

### CODE REVIEW

**Comment by jongogogo** [comment]
@mazaruz We need a better intro. I suggest to create a light weight README.md explaining what this workshop is about: the overall objective and outcomes, a summary on each lab.

**Comment by jack1902** [comment]
Is this workshop similar to the one conducted at AWS re:Inforce? I found that one really helpful!

**Comment by jongogogo** [comment]
The very same one with some updates :)

**Comment by mazaruz** [comment]
> @mazaruz We need a better intro. I suggest to create a light weight README.md explaining what this workshop is about: the overall objective and outcomes, a summary on each lab.

Noted. Let me complete them this weekend

**Comment by mazaruz** [comment]
> Is this workshop similar to the one conducted at AWS re:Inforce? I found that one really helpful!

Yes, it's the very same one. I did few update to make sure everyone can try at their home :)

**Pull request merged**
