### PR TITLE
Fix to Issue 326 - Export and (Un)Deploy-Organization hotfix 

### PR DESCRIPTION
**Pull request by jarrettandrulis**
*Issue #, if available:*
  326
*Description of changes:*
Mistakenly used `session` instead of `my_session` causing an attempt to get region_name from the boto3 Session module rather than the boto3 Session class

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by stefanolczak** [comment]
It should be fixed here also:

https://github.com/awslabs/aws-config-rdk/blob/6c1155bdbd0dd20fc27381b5d3675ba33c60993b/rdk/rdk.py#L3643-L3645

**Comment by stefanolczak** [comment]
It didnt work for me so thats why I reported it.

**Comment by stefanolczak** [comment]
It appears that you just fixed one of the mentioned errors in the "deploy-organization" feature by updating this line:

https://github.com/awslabs/aws-config-rdk/blob/e8b3cae2fba922c54d9e4e69fef356ebb53c9192/rdk/rdk.py#L1839

But it isn't enough because it fails with error like this:

```
Traceback (most recent call last):
  File "/usr/local/bin/rdk", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/rdk/cli.py", line 53, in main
    return_val = my_rdk.process_command()
  File "/usr/local/lib/python3.9/site-packages/rdk/rdk.py", line 490, in process_command
    exit_code = method_to_call()
  File "/usr/local/lib/python3.9/site-packages/rdk/rdk.py", line 1839, in deploy_organization
    layers = self.__get_lambda_layers(my_session,self.args,rule_params)
  File "/usr/local/lib/python3.9/site-packages/rdk/rdk.py", line 3628, in __get_lambda_layers
    if args.generated_lambda_layer:
AttributeError: 'Namespace' object has no attribute 'generated_lambda_layer'
```

To make it work the function `get_deployment_organization_parser()` should be updated by adding those lines:

```
    parser.add_argument('-g', '--generated-lambda-layer', required=False, action='store_true', help='[optional] Forces rdk deploy to use the Python(3.6-lib,3.7-lib,3.8-lib,) lambda layer generated by rdk init --generate-lambda-layer')
    parser.add_argument('--custom-layer-name', required=False, default="rdklib-layer", action='store_true', help='[optional] To use with --generated-lambda-layer, forces the flag to look for a specific lambda-layer name. If omitted, "rdklib-layer" will be used')
```

Can you add it please?

**Comment by stefanolczak** [comment]
Here are my commits that fully fix the organization support:

https://github.com/stefanolczak/aws-config-rdk/commits/export-hotfix

**Comment by stefanolczak** [comment]
Oh unfortunately the "undeploy-organization" functionality in multi-region approach needs a fix. Working on it

**Comment by stefanolczak** [comment]
Additionally it looks like the support for `--lambda-role-name` is broken:
 
 https://github.com/awslabs/aws-config-rdk/blob/e8b3cae2fba922c54d9e4e69fef356ebb53c9192/rdk/rdk.py#L1412-L1415
 https://github.com/awslabs/aws-config-rdk/blob/e8b3cae2fba922c54d9e4e69fef356ebb53c9192/rdk/rdk.py#L1768-L1771
 
The log message says RDK it's looking for role but it uses hardcoded name `Rdk-Lambda-Role` instead.
 
 Also here it doesn't make sense:
 
 https://github.com/awslabs/aws-config-rdk/blob/e8b3cae2fba922c54d9e4e69fef356ebb53c9192/rdk/rdk.py#L3472-L3474
 https://github.com/awslabs/aws-config-rdk/blob/e8b3cae2fba922c54d9e4e69fef356ebb53c9192/rdk/rdk.py#L3576-L3578
 
 It check for `lambda_role_name` but uses `lambda_role_arn` anyway.

**Comment by jarrettandrulis** [comment]
The new commits should fix these issues and enable multi-region support for `deploy-organization` and `undeploy-organization`, thanks for pointing them out @stefanolczak

**Review by stefanolczak — APPROVED** [review]

**Review by rickychau2780 — APPROVED** [review]
lgtm

**Pull request merged**
