### PR TITLE
Feature/ssm automation

### PR DESCRIPTION
**Pull request by singergs**
## Description of feature:
The PR adds the ability to build a SSM Automation Document when a RDK Rule is configured with a remediation.  

Here is a sample snippet of a remediation and pointer to a SSM document. Further down is a sample of a SSM Automation Document
```
   "Remediation": {
      "ConfigRuleName": "ssmPOC",
      "Parameters": {
        "AutomationAssumeRole": {
          "StaticValue": {
            "Values": [
              "arn:aws:iam::012345678901:role/enable-DynomoDB-enableBackups"
            ]
          }
        },
        "DynamoDbTable": {
          "ResourceValue": {
            "Value": "RESOURCE_ID"
          }
        }
      },
      "ResourceType": "AWS::DynamoDB::Table",
      "TargetType": "SSM_DOCUMENT"
    },
    "SSMAutomation": {
        "Document": "/home/ec2-user/environment/rdk-feature-ssm/aws-config-rdk/ssmPOC/ssmautomation.json"
    }

```
The SSMAutomation parameter section will point to a json file that contains the SSM Automation Document --See Below

### The following is a sample SSM Document
```
{

    "description": "Automation Document: Enable Continous BackUp For DynamoDB with change",
    "schemaVersion": "0.3",
    "assumeRole": "{{ AutomationAssumeRole }}",
    "parameters": {
        "DynamoDbTable": {
            "type": "String",
            "description": "(Required) DynamoDb Table"
        },
        "AutomationAssumeRole": {
            "type": "String",
            "description": "(Optional) The ARN of the role that allows Automation to perform the actions on your behalf.",
            "default": ""
        }
    },
    "mainSteps": [
        {
            "name": "enableBackupOnDynomoDbTable",
            "action": "aws:executeAwsApi",
            "inputs": {
                "Service": "dynamodb",
                "Api": "UpdateContinuousBackups",
                "TableName": "{{ DynamoDbTable }}",
                "PointInTimeRecoverySpecification": {
                    "PointInTimeRecoveryEnabled": true
                }
            }
        }
    ]
    
}
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jack1902** [comment]
This still has the issue of needing a role in the account which can be used by automation. Nice addition though. Hope it gets added.

**Comment by singergs** [comment]
Yea, I totally agree that expanding the ability to build a role/policy would complete the addition.  I have a fork with that capability if you want to kick the tires on it.  I haven't made a PR yet.
https://github.com/singergs/aws-config-rdk/tree/feature/ssm-automation-with-iam

**Comment by jinkang23** [comment]
When will he pull request get added?

**Comment by rickychau2780** [comment]
we are not implementing this feature. RDK is designed for writing config rules and spin up its related resources. The resources for auto remediation is considerable to include. However, it is hard to manage the development kit if we have user to input as a json and parse it as cloudformation. We are working on making the case more general to have "rdk deploy" support executing additional cloudformation template or cloudformation template snippet. Therefore, user will provide a cfn template like file for the creation of ssm automation as well as its related resources. This will give user more flexibility on the resources and not restricted by RDK. I will create a branch for this change though. People can clone the branch if they want the change for now.

**Comment by rickychau2780** [comment]
Based on discussion, we are going to add this feature as a beta feature and getting feedbacks. We may have a more generalized solution in the future. Here are the remarks:
1. SSM Automation usually is reused for different purpose. The solution here is bundling a single config rule with a single SSM Automation doc. 
2. SSM Automation related resources are not generated in this solution. Fo example, for a SSM Automation that triggers a SNS topic notification, user is likely have SNS topic created with the SSM Automation. This solution only creates the IAM role for SSM Automation, but not all its related resources. 
3. For creating rules templates, the automation and its role per each rule will counted in the 200 limit of cloudformation template resources. It means, you can have at most 50 rules with remediation, SSM automation and automation iam role in the template.

**Pull request merged**
