### PR TITLE
CLI: Swap to entry_point

### PR DESCRIPTION
**Pull request by bdwyertech**
Use `entry_point` for better cross-platform compatibility

Works under pipenv on Windows and OSX.

Addresses #80

https://packaging.python.org/tutorials/distributing-packages/#scripts

https://stackoverflow.com/questions/23324353/pros-and-cons-of-script-vs-entry-point-in-python-command-line-scripts

#### Pipfile
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
awscli = "*"
rdk = {git = "https://github.com/bdwyertech/aws-config-rdk.git",ref = "cli",editable = true}

[requires]
python_version = "3.6"
```
```
pipenv run rdk --help
usage: rdk [-h] [-p PROFILE] [-k ACCESS_KEY_ID] [-s SECRET_ACCESS_KEY]
           [-r REGION] [-v]
           <command> ...

The RDK is a command-line utility for authoring, deploying, and testing custom
AWS Config rules.

positional arguments:
  <command>             Command to run. Refer to the usage instructions for
                        each command for more details
  <command arguments>   Run `rdk <command> --help` to see command-specific
                        arguments.

optional arguments:
  -h, --help            show this help message and exit
  -p PROFILE, --profile PROFILE
                        [optional] indicate which Profile to use.
  -k ACCESS_KEY_ID, --access-key-id ACCESS_KEY_ID
                        [optional] Access Key ID to use.
  -s SECRET_ACCESS_KEY, --secret-access-key SECRET_ACCESS_KEY
                        [optional] Secret Access Key to use.
  -r REGION, --region REGION
                        Select the region to run the command in.
  -v, --version         Display the version of this tool
```

### CODE REVIEW

**Comment by bdwyertech** [comment]
I'll take a look later on today, I'm sure there is, might need a small tweak looking at the output there.

**Comment by bdwyertech** [comment]
Fixed @michaelborchert 

Looks like it was the method decorator.  Must have been a discrepancy between how Py 2.7 and 3.6+ handles it.

**Comment by michaelborchert** [comment]
Hmm, still getting errors on python2.7:

```
(rdk-dev27) [burner] rdk-dev27 $ rdk sample-ci AWS::EC2::Instance
Traceback (most recent call last):
  File "/Users/mborch/Code/rdk-dev27/bin/rdk", line 10, in <module>
    sys.exit(main())
  File "/Users/mborch/Code/rdk-dev27/lib/python2.7/site-packages/rdk/cli.py", line 17, in main
    my_rdk = rdk.rdk(args)
AttributeError: class rdk has no attribute 'rdk'
```

Also, I've merged in a bunch of other PR's for things like Windows executable support which I think conflict with this one, you should probably pull the latest into your fork.

**Comment by bdwyertech** [comment]
Yep I merged those in. Try deleting your local copy of this branch and checkout a fresh copy as I force pushed,

**Comment by michaelborchert** [comment]
Still getting the same issue, even on a fresh server, git clone, PR pull.  When I pull down your PR to test I get the following merge result that looks like you're behind the awslabs repo:

```
[] aws-config-rdk $ git pull https://github.com/bdwyertech/aws-config-rdk.git cli
From https://github.com/bdwyertech/aws-config-rdk
 * branch            cli        -> FETCH_HEAD
Auto-merging setup.py
Auto-merging rdk/rdk.py
Removing bin/rdk.cmd
Merge made by the 'recursive' strategy.
 bin/rdk     | 26 --------------------------
 bin/rdk.cmd | 32 --------------------------------
 rdk/rdk.py  |  2 +-
 setup.py    |  6 +++++-
 4 files changed, 6 insertions(+), 60 deletions(-)
 delete mode 100644 bin/rdk
 delete mode 100644 bin/rdk.cmd
```

**Comment by bdwyertech** [comment]
I just now started fresh off master and cherry-picked my commits -- one of them removes the `rdk.cmd` as it is no longer necessary when using entry_point.

Curious, you showed git output but did you try running `pip install` in a fresh env?  I tested again on my Mac and Win 10 machine, both Py 3.6 and Py 2.7 and not seeing an issue.

This is how I am testing on both 2.7 and 3.6 using a clean environment
```shell
python -m pip install pipenv
pipenv install -e . --python 3.6
pipenv run rdk --help

pipenv --rm
rm Pipfile
pipenv install -e . --python 2.7
pipenv run rdk --help
```

**Comment by michaelborchert** [comment]
Using either pipenv or virtualenv I can replicate success with running `rdk --help`, but trying to do anything more complicated still results in errors in Python 2.7:
`(rdk-test-python27) [burner] rdk-test-python27 $ rdk create MyTestRule --runtime python3.6 --resource-types AWS::EC2::Instance
Traceback (most recent call last):
  File "/Users/mborch/Code/rdk-test-python27/bin/rdk", line 10, in <module>
    sys.exit(main())
  File "/Users/mborch/Code/rdk-test-python27/lib/python2.7/site-packages/rdk/cli.py", line 17, in main
    my_rdk = rdk.rdk(args)
AttributeError: class rdk has no attribute 'rdk'
`

Do the `create` and `deploy` commands work in your environment?  I've tried in virtualenvs and in system python in an AWS CodeBuild image.

**Comment by bdwyertech** [comment]
I see what it is... Missed a line when I added 2.7 support... Testing on 3.6 now

**Comment by bdwyertech** [comment]
Alright, I think it's good to go now.

Using the six compatibility module to more cleanly handle 2.7 vs 3.x

**Comment by michaelborchert** [comment]
Tested on multiple platforms and multiple python versions, and everything looks good!  Thanks for the contribution, and I really appreciate your patience and perseverance!

**Pull request merged**
